/* =========================================================================
   Family Recipes — data layer
   -------------------------------------------------------------------------
   HOW TO ADD A RECIPE (two ways, both easy):

   1) Easiest: open the website, click "Add recipe", fill the form (or paste
      from Apple Notes). It generates a ready-to-paste recipe block. Copy it
      and paste it into the RECIPES array below, then commit to GitHub.

   2) By hand: copy any recipe object below, change the values, give it a
      unique "id", and add it to the RECIPES array.

   QUANTITY SCALING:
   Each ingredient has { amount, unit, item }. "amount" is the quantity for
   the recipe's base "servings". The site multiplies amount by
   (chosenServings / baseServings) automatically — so scaling Just Works.
   Use amount: null for things like "salt to taste".

   TWO RECIPE SHAPES (both supported):
   • Simple recipe: use top-level  ingredients: [...]  and  steps: [...]
   • Multi-phase recipe (like a pasta with dough + filling + sauce): use
       sections: [ { name: "The Dough", ingredients:[...], steps:[...] }, ... ]
     The Add-form's Apple Notes importer builds these automatically.
   ========================================================================= */

// The two cooks. Add more here if you like (e.g. siblings, dad).
const AUTHORS = {
  you:  { name: "You",  color: "#c0562f" },   // terracotta
  mom:  { name: "Mom",  color: "#5d7355" },   // sage
};

// Smart categories. The "Add" form lets you pick one of these.
const CATEGORIES = [
  { id: "appetizer", label: "Appetizer", color: "#b88a3e" },
  { id: "main",      label: "Main",      color: "#c0562f" },
  { id: "side",      label: "Side",      color: "#5d7355" },
  { id: "soup",      label: "Soup",      color: "#7a3b52" },
  { id: "salad",     label: "Salad",     color: "#6b8e4e" },
  { id: "dessert",   label: "Dessert",   color: "#c0567f" },
  { id: "breakfast", label: "Breakfast", color: "#d68c45" },
  { id: "bread",     label: "Bread",     color: "#a9763e" },
  { id: "drink",     label: "Drink",     color: "#4f7a8e" },
  { id: "sauce",     label: "Sauce",     color: "#8a6d3b" },
];

/* ---- The cookbook. Newest first looks nice but order doesn't matter. ---- */
const RECIPES = [
  {
    id: "white-bean-soup",
    title: "White Bean Soup with Truffle & Bacon Dust",
    author: "you",
    category: "soup",
    description: "A velvety puréed navy bean soup enriched with cream and smoked duck bacon, finished with black truffle and a dusting of crisp bacon.",
    image: "",
    servings: 8,
    prepMin: 30,
    cookMin: 210,
    ingredients: [
      { amount: 2, unit: "lb", item: "dried navy beans (soaked in water 24 hours ahead)" },
      { amount: 13, unit: "", item: "slices smoked duck bacon" },
      { amount: 2, unit: "", item: "celery stalks, chopped" },
      { amount: 1, unit: "", item: "large white or yellow onion, minced" },
      { amount: 5, unit: "cloves", item: "garlic, peeled and whole" },
      { amount: 2, unit: "", item: "stems fresh thyme" },
      { amount: 1, unit: "gallon", item: "chicken stock" },
      { amount: 0.25, unit: "lb", item: "butter" },
      { amount: 1, unit: "cup", item: "heavy cream" },
      { amount: null, unit: "", item: "salt and pepper, to taste" },
      { amount: 0.25, unit: "cup", item: "chives, thinly sliced" },
      { amount: 4, unit: "tbsp", item: "black truffle oil & purée" },
      { amount: 0.25, unit: "cup", item: "bacon dust (from the crisped bacon)" },
    ],
    steps: [
      { text: "Cook the bacon in the oven until very crispy, **reserving the rendered fat**.", tip: "Save every drop of that fat — it's the flavour base the whole soup is built on." },
      { text: "Finely chop the crisped bacon with a knife or food processor and reserve as garnish (this is your bacon dust)." },
      { text: "Gently cook the minced onions and celery in the bacon fat over medium heat for **6–10 minutes**, stirring constantly, taking care not to brown.", tip: "Sweat, don't sear — browning here turns the delicate base bitter and muddies the pale colour." },
      { text: "When the onions are translucent, add the drained soaked beans, thyme, garlic, butter, cream and chicken stock. Bring to a boil, then reduce to a **very gentle simmer for 1.5 hours**, covered, stirring occasionally.", tip: "A bare simmer keeps the beans intact and the cream from breaking — a hard boil will curdle the dairy." },
      { text: "When the beans are tender, remove from the heat and let cool **1 hour** before puréeing to a velvety texture in a blender. Adjust salt and pepper.", tip: "Let it cool first — blitzing scalding soup builds steam pressure that can blow the lid off. Blend in batches, lid cracked." },
      { text: "Garnish each bowl with sliced chives, bacon dust, and a swirl of truffle oil/purée.", tip: "Add the truffle oil off the heat, at the very end — its aroma is volatile and cooking destroys it." },
    ],
    tips: [
      "Soaking the beans a full 24 hours is what gives the final purée its silky, skin-free texture.",
      "Pass the purée through a fine sieve for a truly restaurant-smooth, glossy soup.",
      "Balance the richness with a few extra drops of acid (lemon) if it tastes flat before serving.",
    ],
  },
  {
    id: "marzipan",
    title: "Marzipan",
    author: "mom",
    category: "dessert",
    description: "Homemade almond marzipan cooked from scratch — blanched almonds and a clear sugar syrup, bound with whipped egg white, then shaped into little sweets.",
    image: "",
    servings: 12,
    prepMin: 60,
    cookMin: 30,
    sections: [
      {
        name: "Preparing the Almonds",
        ingredients: [
          { amount: 600, unit: "g", item: "almonds" },
          { amount: 1.5, unit: "cup", item: "sugar (a little more if needed)" },
          { amount: 1, unit: "tsp", item: "lemon juice" },
          { amount: 1, unit: "tbsp", item: "almond extract" },
          { amount: 1, unit: "", item: "egg white" },
        ],
        steps: [
          { text: "Place the almonds in hot water, bring to a boil, let boil **1 minute**, then remove from heat.", tip: "The quick boil loosens the skins; any longer and the almonds start to soften and lose bite." },
          { text: "Peel the almonds and let them dry for a couple of hours.", tip: "Dry almonds grind to a fine, fluffy crumb — damp ones turn to oily paste in the processor." },
          { text: "Grind the dried almonds in a mixer until they reach the consistency of **thick couscous**." },
        ],
      },
      {
        name: "Cooking the Marzipan",
        ingredients: [],
        steps: [
          { text: "In a wide saucepan add the **sugar** (1.5 cups, a little more) and pour in just enough water to cover it.", tip: "A wide pan gives the syrup more surface area, so it clears and cooks evenly without hot spots." },
          { text: "Add the **lemon juice** and **almond extract**.", tip: "The lemon juice prevents the sugar from crystallising and keeps the syrup smooth and clear." },
          { text: "Heat until the sugar becomes a **clear solution**." },
          { text: "Meanwhile, whisk one **egg white** until white and fluffy." },
          { text: "Once the syrup is clear, add the almonds and keep mixing — make sure the bottom doesn't overcook.", tip: "Stir constantly and scrape the bottom; almond paste scorches fast over direct heat." },
          { text: "When the almonds look slightly dry, quickly fold in the egg white, mixing fast so it doesn't scramble into an omelette." },
          { text: "Continue mixing until the paste becomes even drier." },
          { text: "When it's dry enough, let the mixture cool and dry for an **hour or two**." },
        ],
      },
      {
        name: "Shaping",
        ingredients: [],
        steps: [
          { text: "Take a little marzipan, add it to the mixer, and while it runs add a touch of water until it forms a ball.", tip: "Add water a few drops at a time — too much and the paste turns sticky and won't hold a shape." },
          { text: "Wet the countertop, then roll the ball out into strands and cut on a diagonal to form the marzipan shapes.", tip: "A lightly wet surface stops the marzipan sticking and gives the cut pieces a clean, glossy edge. Keep adding water as needed and finish each into a pushariko." },
        ],
      },
    ],
    tips: [
      "Work in small batches when shaping so the marzipan doesn't dry out before you cut it.",
      "Mark each piece with a toothpick for the traditional decorative pattern.",
    ],
  },
  {
    id: "tres-leches",
    title: "Tres Leches Cake",
    author: "you",
    category: "dessert",
    description: "A light sponge soaked in three milks until lusciously wet, topped with billowy whipped cream, dulce de leche and fresh strawberries.",
    image: "",
    servings: 12,
    prepMin: 40,
    cookMin: 25,
    sections: [
      {
        name: "The Sponge",
        ingredients: [
          { amount: 5, unit: "", item: "eggs, separated" },
          { amount: 1, unit: "cup", item: "white sugar, divided" },
          { amount: 4.88, unit: "oz", item: "all-purpose flour" },
          { amount: 1.5, unit: "tsp", item: "baking powder" },
          { amount: 0.25, unit: "tsp", item: "salt" },
          { amount: 0.33, unit: "cup", item: "milk" },
          { amount: 0.75, unit: "tsp", item: "vanilla extract" },
          { amount: null, unit: "", item: "vegetable oil, for greasing pans" },
        ],
        steps: [
          { text: "Preheat the oven to **350°F**. Separate the eggs, whites into a stand-mixer bowl, yolks set aside." },
          { text: "Whip the whites on high with the whisk attachment, slowly adding **½ cup sugar**, until **stiff peaks** form. Set the meringue aside.", tip: "Stiff, glossy peaks are what make this sponge airy enough to drink up the milks — under-whipped whites give a dense cake." },
          { text: "Beat the yolks with the other **½ cup sugar** on medium with the paddle for about **2 minutes**, until pale and smooth." },
          { text: "In a separate bowl, whisk together the flour, baking powder and salt." },
          { text: "Add the **milk** and **vanilla** to the yolks and mix until combined, then mix in the dry ingredients until just combined." },
          { text: "Gently fold the meringue into the batter, being careful not to deflate the whites.", tip: "Fold in thirds with a light hand — every bit of air you keep now becomes height and sponginess later." },
          { text: "Line two pans with parchment and grease with vegetable oil. Pour the batter evenly between them and smooth the tops." },
          { text: "Bake at **350°F for 20–25 minutes**, until a tester comes out clean." },
        ],
      },
      {
        name: "Soak & Finish",
        ingredients: [
          { amount: 1, unit: "", item: "can (14 oz) sweetened condensed milk" },
          { amount: 1, unit: "", item: "can (12 oz) evaporated milk" },
          { amount: 4, unit: "oz", item: "whole milk" },
          { amount: null, unit: "", item: "heavy whipping cream, sugar & vanilla (for the topping)" },
          { amount: null, unit: "", item: "dulce de leche, to drizzle" },
          { amount: null, unit: "", item: "thinly sliced strawberries, to garnish" },
        ],
        steps: [
          { text: "Cool the cakes **1 hour**, remove from the pans and peel off the parchment, then return each to its pan and poke holes all over the tops with a fork.", tip: "The fork holes are essential — they're the channels the three milks travel through to soak the cake evenly." },
          { text: "Combine the **condensed, evaporated and whole milk**, then ladle over both cakes. Cover and refrigerate **at least 6 hours, preferably overnight**.", tip: "Pour slowly and let each ladle absorb before the next — the cake should be saturated but never sitting in a puddle." },
          { text: "Whip the **heavy cream** with sugar and vanilla to stiff peaks." },
          { text: "Place one cake layer on a stand, cover with whipped cream, drizzle with dulce de leche, and garnish with sliced strawberries. Serve and enjoy." },
        ],
      },
    ],
    tips: [
      "Overnight soaking is worth the wait — the milks need time to reach the centre for that signature wet-but-not-soggy crumb.",
      "Chill the mixing bowl before whipping the cream so it holds its peaks against the moist cake.",
    ],
  },
  {
    id: "key-lime-pie",
    title: "Key Lime Pie",
    author: "mom",
    category: "dessert",
    description: "A tangy citrus custard in a buttery biscuit crust, topped with lightly sweetened whipped cream. Made, as always, with love and patience.",
    image: "",
    servings: 8,
    prepMin: 25,
    cookMin: 25,
    ingredients: [
      { amount: 170, unit: "g", item: "biscuits (animal crackers work well)" },
      { amount: 100, unit: "g", item: "butter, melted" },
      { amount: 3, unit: "", item: "egg yolks" },
      { amount: 1, unit: "", item: "container (14 oz) sweetened condensed milk" },
      { amount: null, unit: "", item: "grated zest of 2 lemons" },
      { amount: 0.5, unit: "cup", item: "fresh lemon juice" },
      { amount: null, unit: "", item: "small container of cream (for topping)" },
      { amount: null, unit: "", item: "vanilla extract (a smidge, for the cream)" },
    ],
    steps: [
      { text: "Make the crust: grind the biscuits and mix with the melted butter. Grease the pie pan (butter is best), press the crumbs over the bottom and up the sides, and bake at **350°F for 8–10 minutes**.", tip: "Don't over-bake the crust now — it bakes again with the filling, and a too-dark crust turns bitter." },
      { text: "Make the filling: beat the egg yolks on medium until light and fluffy. With the mixer running, slowly add the condensed milk and beat **4–5 minutes**.", tip: "Beating the yolks until pale and aerated is what gives the custard its silky set without any starch." },
      { text: "Add the lemon juice and zest and mix in.", tip: "The acid in the juice thickens the condensed milk instantly — once it's in, the filling will start to set, so pour promptly." },
      { text: "Fill the crust and bake in the **lower third** of the oven about **15 minutes**, until the center is just stabilized. Cool, then refrigerate at least **5 hours**.", tip: "The center should still jiggle slightly when you pull it — it firms up completely in the fridge." },
      { text: "For the top: chill the mixer bowl in the freezer 15 minutes, then whip the cream to stiff peaks with a smidge of vanilla and spread over the chilled pie.", tip: "A cold bowl and beaters whip cream faster and to a more stable peak that won't weep on the pie." },
    ],
    tips: [
      "Most importantly — make it with love and patience. Everything you do, do with love. :) :)",
      "Use freshly squeezed juice; bottled lime/lemon juice tastes flat and dulls the custard.",
    ],
  },
  {
    id: "mirits-chocolate-cake",
    title: "Mirit's Chocolate Cake",
    author: "mom",
    category: "dessert",
    description: "Layers of crisp hazelnut-cocoa meringue between clouds of rich dark chocolate mousse, crowned with roasted almonds. A showstopper.",
    image: "",
    servings: 10,
    prepMin: 60,
    cookMin: 75,
    sections: [
      {
        name: "The Hazelnut Meringue",
        ingredients: [
          { amount: 250, unit: "g", item: "roasted hazelnuts (2 cups)" },
          { amount: 2.5, unit: "tsp", item: "cocoa powder" },
          { amount: 4, unit: "", item: "egg whites" },
          { amount: 250, unit: "g", item: "powdered sugar, sifted" },
        ],
        steps: [
          { text: "Heat the oven to **285°F**." },
          { text: "Grind the hazelnuts with the cocoa powder in a food processor to fine crumbs." },
          { text: "Whip the egg whites to a white foam, then add the powdered sugar gradually while whipping to a stable, flexible meringue. Fold in the nut mixture with a spatula.", tip: "Add the sugar slowly and keep whipping to glossy peaks — a stable meringue is what keeps the baked layers crisp." },
          { text: "Line 4 flat pans with baking paper. On each, draw a **23 cm circle** (trace inside a baking pan, slightly smaller than the pan), then flip the papers so the drawn side faces down." },
          { text: "Spread about a quarter of the meringue on each circle into an even **0.5 cm** layer." },
          { text: "Bake all four together for **at least 1 hour**, until crisp, baked and dry, then remove and cool.", tip: "Low and slow dries the meringue all the way through — if it's still chewy in the middle the layers will soften under the mousse." },
        ],
      },
      {
        name: "The Chocolate Mousse",
        ingredients: [
          { amount: 400, unit: "g", item: "dark chocolate" },
          { amount: 0.67, unit: "cup", item: "milk" },
          { amount: 2, unit: "tbsp", item: "brandy or rum" },
          { amount: 2, unit: "tsp", item: "vanilla extract" },
          { amount: 473, unit: "ml", item: "heavy whipping cream" },
          { amount: 100, unit: "g", item: "blanched almonds, sliced & roasted (to decorate)" },
        ],
        steps: [
          { text: "Melt the chocolate in a bain-marie (a heatproof bowl over a pot of simmering water), stirring until smooth.", tip: "Keep the bowl off the water and the heat low — any drop of water or too much heat will seize the chocolate." },
          { text: "Heat the milk and stir it into the chocolate. Mix in the brandy/rum and vanilla, transfer to a large bowl, and let cool until **lukewarm**.", tip: "Cool to lukewarm before adding cream — too hot and it melts the cream; too cold and the chocolate seizes into chips." },
          { text: "Whip the cream to firm, flexible peaks. Fold about a third into the lukewarm chocolate to lighten it, then fold in the rest.", tip: "Lighten first with a third of the cream, then fold the rest gently to keep the mousse airy." },
        ],
      },
      {
        name: "Assemble",
        ingredients: [],
        steps: [
          { text: "Place one meringue circle in the bottom of the round pan you drew with (or on a serving plate)." },
          { text: "Spread a quarter of the mousse over the meringue." },
          { text: "Repeat to build **four meringue layers**, finishing with a layer of mousse (and cream on the sides if serving immediately)." },
          { text: "Decorate with the roasted sliced almonds.", tip: "Chill the assembled cake a few hours so the layers set and slice cleanly." },
        ],
      },
    ],
    tips: [
      "Build the cake a day ahead — resting overnight lets the meringue marry with the mousse for a melt-in-the-mouth texture.",
      "Use a hot, dry knife to cut clean slices through the crisp layers.",
    ],
  },
  {
    id: "ratatouille",
    title: "Ratatouille (Confit Byaldi)",
    author: "you",
    category: "side",
    description: "The refined, layered version — thinly shingled summer vegetables fanned over a roasted red pepper and tomato sauce, slow-roasted until silky.",
    image: "",
    servings: 6,
    prepMin: 45,
    cookMin: 90,
    ingredients: [
      { amount: 6, unit: "", item: "large roma tomatoes, divided" },
      { amount: 2, unit: "", item: "red bell peppers, seeded and left whole" },
      { amount: 2, unit: "tbsp", item: "tomato paste" },
      { amount: 0.5, unit: "cup", item: "beef stock" },
      { amount: 0.5, unit: "cup", item: "water" },
      { amount: 2, unit: "sprigs", item: "rosemary, picked, divided" },
      { amount: 2, unit: "sprigs", item: "thyme, picked" },
      { amount: 1, unit: "clove", item: "garlic" },
      { amount: 0.5, unit: "", item: "small onion" },
      { amount: 1, unit: "", item: "small shallot" },
      { amount: 4, unit: "tbsp", item: "butter" },
      { amount: 3, unit: "tbsp", item: "olive oil, divided" },
      { amount: 2, unit: "", item: "medium green squash" },
      { amount: 2, unit: "", item: "medium yellow squash" },
      { amount: 3, unit: "", item: "medium baby eggplants" },
      { amount: 1, unit: "tsp", item: "kosher salt" },
      { amount: 1, unit: "tsp", item: "freshly ground pepper" },
      { amount: 5, unit: "leaves", item: "fresh Italian parsley, torn" },
    ],
    steps: [
      { text: "Cut a small **X** in the bottom of 4 roma tomatoes. Blanch in boiling water under a minute, until the cuts just begin to split, then plunge into ice water and cool completely. Set aside.", tip: "The X plus the ice bath makes the skins slip off effortlessly — over-blanching cooks the flesh and makes it mushy." },
      { text: "Char the **2 bell peppers** directly over a high gas flame, turning, until blackened on all sides. Cover with foil **5 minutes**, then peel.", tip: "Steaming under foil loosens the charred skin so it peels cleanly — don't rinse under water or you wash away the smoky flavour." },
      { text: "Blend the peeled peppers with the remaining tomatoes, leaves of one rosemary sprig, thyme, garlic, onion, stock, water, and 1 tbsp olive oil until completely smooth." },
      { text: "Preheat the oven to **300°F**. With a very sharp knife, slice the tomatoes **1/8-inch** thick; with a mandolin, slice the squash and eggplant **1/8-inch** thick.", tip: "Uniform 1/8-inch slices are key — even thickness means every piece cooks at the same rate and the fan looks pristine." },
      { text: "Spread a thin layer of the pepper sauce in a shallow roaster. Shingle the vegetables on top — eggplant, tomato, yellow squash, green squash — repeating the pattern around the edge, each slice overlapping the last by just under 1/4 inch. Continue in rings inward until full.", tip: "Stand the slices up at a steep angle and pack them snugly; they shrink as they roast, so tighter now means a tidy fan later." },
      { text: "Finely chop the remaining rosemary and sprinkle over with 1 tbsp olive oil, salt and pepper. Cover with a parchment round and roast **90 minutes**, removing the parchment for the final 20 minutes.", tip: "The parchment cartouche steams the vegetables tender without drying them; removing it at the end lets the tops caramelize." },
      { text: "When the vegetables are soft but still hold their shape, plate with a ring mold, stacking vertically then staggering a layer on top. Drizzle a circle of pepper sauce mixed with olive oil around it, garnish with torn parsley, and serve." },
    ],
    tips: [
      "Salt the eggplant slices before assembling to draw out bitterness and excess water.",
      "Toss the squash with olive oil and thyme before shingling for extra fragrance.",
      "Serve warm; the dish is even better made a day ahead and gently reheated.",
    ],
  },
  {
    id: "pot-de-creme",
    title: "Pot de Crème",
    author: "you",
    category: "dessert",
    description: "Intensely silky dark-chocolate custard pots, made the easy way by melting chocolate straight into hot cream and enriching with egg yolks.",
    image: "",
    servings: 13,
    prepMin: 20,
    cookMin: 35,
    ingredients: [
      { amount: null, unit: "", item: "good-quality dark chocolate (70%, e.g. Tony's Chocolonely)" },
      { amount: null, unit: "", item: "heavy cream" },
      { amount: 8, unit: "", item: "egg yolks (per 2 servings — scale up accordingly)" },
      { amount: null, unit: "", item: "orange extract (added after cooling)" },
    ],
    steps: [
      { text: "Melt the chocolate **straight into the hot heavy cream**, stirring until smooth and glossy.", tip: "Melting the chocolate directly into hot cream gives the smoothest ganache base with no seizing — keep stirring until it's mirror-glossy." },
      { text: "Whisk in the egg yolks (about 8 yolks per 2 servings) to enrich and set the custard." },
      { text: "Once the mixture has cooled a little, stir in the orange extract.", tip: "Add the orange extract only after it cools slightly — heat drives off its aroma, so late addition keeps it bright." },
      { text: "Divide into small pots and chill until set." },
    ],
    tips: [
      "Use the best dark chocolate you can — with so few ingredients, the chocolate is the whole dessert.",
      "Strain the custard before potting for an ultra-smooth, professional finish.",
    ],
  },
  {
    id: "alfajores",
    title: "Alfajores",
    author: "you",
    category: "dessert",
    description: "Delicate, melt-in-your-mouth cornstarch shortbread sandwiched with dulce de leche and rolled in shredded coconut.",
    image: "",
    servings: 18,
    prepMin: 90,
    cookMin: 9,
    ingredients: [
      { amount: 1, unit: "cup", item: "all-purpose flour" },
      { amount: 1.25, unit: "cup", item: "corn starch" },
      { amount: 1, unit: "tsp", item: "baking powder" },
      { amount: 0.25, unit: "tsp", item: "salt" },
      { amount: 170, unit: "g", item: "unsalted butter, room temperature" },
      { amount: 133, unit: "g", item: "granulated sugar" },
      { amount: null, unit: "", item: "lemon zest" },
      { amount: null, unit: "", item: "egg yolks" },
      { amount: null, unit: "", item: "vanilla extract" },
      { amount: null, unit: "", item: "dulce de leche, to fill" },
      { amount: null, unit: "", item: "shredded coconut, to roll" },
    ],
    steps: [
      { text: "Whisk the flour, corn starch, baking powder and salt in a large bowl and set aside." },
      { text: "Beat the room-temperature butter, lemon zest and sugar on medium for about **3 minutes**, until light and fluffy.", tip: "Properly creaming the butter and sugar aerates the dough — this is what makes alfajores so tender they dissolve on the tongue." },
      { text: "Beat in the yolks one at a time, then the vanilla. Scrape the bowl and mix once more." },
      { text: "Add the dry mixture to the wet and mix until just combined. Press into a disk, wrap, and refrigerate at least **1 hour** (you can split into two batches).", tip: "Chilling firms the high-cornstarch dough so it cuts cleanly — warm dough tears and spreads." },
      { text: "Preheat to **350°F**. Let the dough soften slightly, roll out on a lightly floured surface to about **1/8 inch**, cut into circles, and bake **~9 minutes**, rotating halfway, until the edges are just golden.", tip: "Pull them the instant the edges turn pale gold — these cookies should stay blond and powdery, never browned." },
      { text: "Sandwich two cookies with a teaspoon or two of dulce de leche, press so it spreads to the edge, then roll the exposed filling in shredded coconut." },
    ],
    tips: [
      "Don't overwork the dough; the high cornstarch ratio is what gives the signature sandy, melting texture.",
      "Chill cut shapes again for a few minutes before baking so they keep crisp edges.",
    ],
  },
  {
    id: "duck-confit",
    title: "Duck Confit",
    author: "you",
    category: "main",
    description: "Duck legs cured in salt and slow-poached in their own fat until meltingly tender, then crisped to order. Keeps for weeks in the fat.",
    image: "",
    servings: 6,
    prepMin: 30,
    cookMin: 210,
    ingredients: [
      { amount: 6, unit: "", item: "duck legs" },
      { amount: 3, unit: "tbsp", item: "kosher salt" },
      { amount: 6, unit: "cup", item: "duck fat (enough to cover the legs)" },
      { amount: 12, unit: "", item: "juniper berries, smashed (optional)" },
      { amount: 2, unit: "", item: "bay leaves" },
      { amount: 1, unit: "tbsp", item: "cracked black pepper" },
    ],
    steps: [
      { text: "Coat the duck legs in coarse salt and refrigerate on a rack, **uncovered, overnight** (24 hours). The next day, brush off the salt with a dry brush or cloth.", tip: "The uncovered overnight cure both seasons the meat deep and dries the skin — drier skin crisps far better later." },
      { text: "Melt the duck fat over a very low flame." },
      { text: "Place the legs in a deep roasting pan and submerge completely in the fat (with the juniper, bay and pepper).", tip: "Leaving the very tops just above the fat lets the skin crisp while the meat below stays submerged and silky." },
      { text: "Cook at **250°F (120°C) for 3–4 hours**, until the meat falls easily off the bone and pulls away to expose it.", tip: "It's done when the meat shrinks back from the bone — low and slow is the whole point, don't rush the temperature up." },
      { text: "Serve immediately, or store the legs submerged in the fat in the fridge for **3–4 weeks**." },
      { text: "To serve, crisp the legs skin-side down in a little duck fat over medium heat for a few minutes (or under the broiler on a sheet)." },
    ],
    tips: [
      "Cook's note: I left a little skin above the fat for crispness, ran it about 3 hrs 20 min, and started at 240°F on the bottom rack before moving to the middle after 1.5 hours.",
      "Strain and save the cooking fat — it's gold for roasting potatoes and future confit.",
    ],
  },
  {
    id: "risotto-truffle",
    title: "Truffle Risotto",
    author: "you",
    category: "main",
    description: "A creamy Parmigiano risotto perfumed with truffle dust and finished with cream and a squeeze of lemon — luxurious on its own or as the base for arancini.",
    image: "",
    servings: 4,
    prepMin: 15,
    cookMin: 35,
    ingredients: [
      { amount: 3.5, unit: "cup", item: "low-sodium chicken stock" },
      { amount: 0.5, unit: "tsp", item: "truffle dust" },
      { amount: 4, unit: "tbsp", item: "unsalted butter, divided" },
      { amount: 1, unit: "", item: "medium onion, diced" },
      { amount: 2, unit: "cloves", item: "garlic" },
      { amount: 1, unit: "cup", item: "arborio rice" },
      { amount: 0.5, unit: "cup", item: "dry white wine (Sauvignon Blanc)" },
      { amount: 1, unit: "cup", item: "Parmigiano Reggiano" },
      { amount: 0.25, unit: "cup", item: "heavy cream" },
      { amount: 1, unit: "tbsp", item: "fresh lemon juice" },
      { amount: null, unit: "", item: "salt and freshly ground black pepper" },
    ],
    steps: [
      { text: "Bring the stock to a simmer in a pot, then keep it warm over low heat.", tip: "Always add warm stock to risotto — cold stock shocks the rice and stalls the starch release that makes it creamy." },
      { text: "Melt 2 tbsp butter in a saucepan over medium. Cook the diced onion **4–5 minutes** until soft but not browned, then add the garlic and cook **1 minute** more." },
      { text: "Stir in the rice and season with **1½ tsp salt**. Cook **~3 minutes**, stirring, until the grains turn translucent at the edges.", tip: "Toasting the rice until the edges go glassy gives the finished risotto its nutty backbone and keeps the grains separate." },
      { text: "Add the wine and cook **~2 minutes** until the pan is almost dry." },
      { text: "Ladle in **1 cup stock**, simmer and stir until absorbed (~4 min). Add another cup, stir until mostly absorbed (5–7 min). Add the final **1½ cups** and cook **9–11 minutes**, stirring often, until the rice is creamy but toothsome.", tip: "Add stock one ladle at a time and stir constantly — that friction coaxes out the starch that makes risotto velvety without cream." },
      { text: "Off the heat, stir in 2 tbsp butter, the Parmesan, cream, lemon juice, **1 tsp pepper** and the truffle dust. Season with salt and let cool.", tip: "Beat the butter and cheese in vigorously off the heat (the 'mantecatura') for that glossy, emulsified finish." },
    ],
    tips: [
      "Risotto waits for no one — serve it the moment it's done, loose enough to spread slightly on the plate.",
      "Spread leftover risotto on a tray and chill it to make arancini the next day.",
    ],
  },
  {
    id: "arancini",
    title: "Mozzarella Arancini",
    author: "you",
    category: "appetizer",
    description: "Crisp golden rice balls with a molten mozzarella center, made from chilled truffle risotto, breaded in panko and deep-fried.",
    image: "",
    servings: 8,
    prepMin: 60,
    cookMin: 30,
    ingredients: [
      { amount: null, unit: "", item: "1 batch chilled Truffle Risotto (see recipe)" },
      { amount: null, unit: "", item: "low-moisture mozzarella, cut into pieces" },
      { amount: 2, unit: "cup", item: "panko" },
      { amount: 0.5, unit: "cup", item: "all-purpose flour" },
      { amount: 2, unit: "", item: "large eggs" },
      { amount: 6, unit: "cup", item: "canola oil, for frying" },
    ],
    steps: [
      { text: "Spread the risotto in an even layer on a parchment-lined sheet and chill **at least 1 hour** (up to 4; cover after 1 hour so it doesn't skin over).", tip: "Cold, firm risotto is essential — warm risotto won't hold a ball and will burst in the oil." },
      { text: "Scoop **~¼ cup** risotto, flatten into a patty, place 2–3 pieces of mozzarella in the center, then pinch and roll into a **2-inch ball**. Freeze the balls **1 hour**.", tip: "Fully enclose the cheese with no cracks, then freeze — a sealed, cold ball keeps the molten center in and the oil out." },
      { text: "Set up a breading station: dredge each ball in flour, then beaten egg, then panko, pressing gently to adhere. Chill while the oil heats.", tip: "Press the panko on firmly and chill again — a solid, cold crust fries up shatteringly crisp." },
      { text: "Heat the oil to **350°F**. Fry in batches until deeply golden, **6–8 minutes**. Drain on paper towels and season with salt. Serve warm with sauce.", tip: "Keep the oil steady at 350°F and don't crowd the pot — too many at once drops the temperature and makes them greasy." },
    ],
    tips: [
      "Use low-moisture mozzarella so the center melts to a stretch without releasing watery liquid that splatters.",
      "Make the risotto a day ahead specifically for arancini — day-old risotto shapes best.",
    ],
  },
  {
    id: "cheese-souffle",
    title: "Cheese Soufflé",
    author: "you",
    category: "appetizer",
    description: "Airy twice-cheese soufflés on a classic béchamel base — tall, golden, and trembling. Serve the instant they come out of the oven.",
    image: "",
    servings: 7,
    prepMin: 30,
    cookMin: 15,
    sections: [
      {
        name: "Mise en Place",
        ingredients: [
          { amount: null, unit: "", item: "butter, melted (for the ramekins) + 3 tbsp for the béchamel" },
          { amount: 1, unit: "", item: "bar Gruyère cheese, grated" },
          { amount: 1, unit: "", item: "bar vintage English cheddar, grated" },
          { amount: 4, unit: "", item: "egg whites" },
          { amount: 3, unit: "", item: "egg yolks" },
          { amount: 3, unit: "tbsp", item: "flour" },
          { amount: 2, unit: "cup", item: "milk" },
          { amount: null, unit: "", item: "salt, pepper, nutmeg, dry mustard" },
          { amount: null, unit: "", item: "lemon (to clean the bowl) + a sprinkle of juice for the whites" },
        ],
        steps: [
          { text: "Preheat the oven to **365°F**. Brush melted butter inside **7 ramekins** and chill them so the butter sets.", tip: "Brush the butter in upward strokes and chill — those vertical tracks help the soufflé climb straight up the sides." },
          { text: "Grate the Gruyère and cheddar and set aside. Wipe the mixer bowl with lemon to remove any fat, then set 4 whites in it and 3 yolks in a separate bowl.", tip: "Any trace of fat stops egg whites from whipping — the lemon wipe guarantees a spotless bowl and maximum volume." },
          { text: "Measure the flour and milk and have everything ready before you start cooking." },
        ],
      },
      {
        name: "Béchamel & Whites",
        ingredients: [],
        steps: [
          { text: "Melt 3 tbsp butter in a pan over medium-low. When it just bubbles, whisk in 3 tbsp flour and cook, **stirring constantly so it doesn't burn**, then gradually whisk in the 2 cups milk.", tip: "Never stop whisking the roux — constant motion is what keeps it lump-free and stops the flour catching." },
          { text: "When it simmers, take it off the heat and add salt, pepper, nutmeg and a sprinkle of dry mustard." },
          { text: "Gradually stir in the cheese to taste until smooth, then beat in the **egg yolks one by one** until smooth, and let sit.", tip: "Add the yolks off the heat and one at a time so they enrich the sauce without scrambling." },
          { text: "In the cleaned mixer, whip the **4 egg whites** with a little salt and a sprinkle of lemon juice, starting low and increasing speed, until firm and holding a peak.", tip: "Whip to firm but not dry peaks — over-whipped whites turn grainy and won't fold in evenly." },
        ],
      },
      {
        name: "Fold, Fill & Bake",
        ingredients: [],
        steps: [
          { text: "Stir a little of the whites into the béchamel to lighten it, then pour all the béchamel into the whites and **fold gently** until no white streaks remain — don't deflate.", tip: "Fold, never stir — cutting down through the center and lifting over keeps the air that gives the soufflé its rise." },
          { text: "Butter the ramekins once more, add flour, spin to coat, and tap out the excess.", tip: "The butter-and-flour lining gives the batter grip to climb — bare ramekins make soufflés that slump." },
          { text: "Fill each ramekin to **¾**, then run a finger around the inside edge so it rises evenly.", tip: "That clean moat around the rim releases the batter from the lip so it pushes straight up into a top hat." },
          { text: "Sprinkle cheese on top and bake **~15 minutes**. Serve immediately.", tip: "Do not open the oven while baking, and rush them to the table — a soufflé starts to fall the moment it leaves the heat." },
        ],
      },
    ],
    tips: [
      "Have everyone seated before the soufflés come out — they wait for no one.",
      "Room-temperature egg whites whip to greater volume than cold ones.",
    ],
  },
  {
    id: "crepes",
    title: "Crêpes",
    author: "you",
    category: "breakfast",
    description: "Thin, tender vanilla crêpes — a simple batter that's endlessly versatile, sweet or savory.",
    image: "",
    servings: 4,
    prepMin: 10,
    cookMin: 20,
    ingredients: [
      { amount: 3, unit: "cup", item: "whole milk" },
      { amount: 4, unit: "", item: "eggs" },
      { amount: 2, unit: "cup", item: "flour" },
      { amount: 0.5, unit: "cup", item: "sugar" },
      { amount: null, unit: "", item: "vanilla paste" },
      { amount: 2, unit: "tbsp", item: "butter, melted" },
    ],
    steps: [
      { text: "Whisk together the milk, eggs, flour, sugar, vanilla paste and melted butter until completely smooth.", tip: "Blend or whisk until lump-free, then rest the batter 30 minutes if you can — it relaxes the gluten for tender, lacy crêpes." },
      { text: "Heat a non-stick pan over medium, lightly butter it, and pour in a thin layer of batter, swirling to coat.", tip: "Pour, then immediately tilt and swirl the pan — the thinner you spread it, the more delicate the crêpe." },
      { text: "Cook until the edges lift and the underside is golden, then flip and cook briefly on the second side." },
    ],
    tips: [
      "The first crêpe is always a test — it seasons the pan; don't worry if it's not perfect.",
      "Stack finished crêpes under a towel to keep them soft and pliable.",
    ],
  },
  {
    id: "croissants",
    title: "Croissants & Pain au Chocolat",
    author: "you",
    category: "bread",
    description: "A proper laminated croissant — détrempe and butter block folded into hundreds of paper-thin layers over two days, baked to a shattering, honeycombed crumb.",
    image: "",
    servings: 8,
    prepMin: 180,
    cookMin: 35,
    sections: [
      {
        name: "Détrempe (Dough) — Day 1",
        ingredients: [
          { amount: 605, unit: "g", item: "all-purpose or bread flour (11–11.5% protein), plus more for dusting" },
          { amount: 66, unit: "g", item: "granulated sugar" },
          { amount: 12, unit: "g", item: "kosher salt" },
          { amount: 7, unit: "g", item: "active dry yeast" },
          { amount: 214, unit: "g", item: "water, room temperature" },
          { amount: 120, unit: "g", item: "whole milk, room temperature" },
          { amount: 57, unit: "g", item: "unsalted butter, chilled, in 1/2-inch pieces" },
        ],
        steps: [
          { text: "Twenty-four hours before serving, combine the flour, sugar, salt and yeast in a stand mixer with the dough hook and stir." },
          { text: "Make a well, pour in the water and milk, and mix on low until a tight, smooth dough forms around the hook, about **5 minutes**. Rest, covered with a damp towel, **10 minutes**." },
          { text: "On medium-low, add the chilled butter pieces all at once and mix, scraping down, until the dough is **very smooth, stretchy and not at all sticky**, 8–10 minutes.", tip: "Keep going until the dough passes a windowpane test — strong gluten now is what holds the laminated layers later." },
          { text: "Form a ball, place seam-down, and cut two deep perpendicular slashes forming a **+**. Place slashed-side up in the bowl, cover, and rise at room temperature to **1.5× its size**, 45 min–1 hour. Refrigerate **at least 4 hours, up to 12**.", tip: "The cross-slash helps the dough relax into a square as it chills, making it far easier to roll evenly tomorrow." },
        ],
      },
      {
        name: "Butter Block",
        ingredients: [
          { amount: 340, unit: "g", item: "unsalted European-style butter (82%+ fat), chilled" },
        ],
        steps: [
          { text: "Place the sticks side by side on parchment, fold into a packet, and beat with a rolling pin into a pliable slab. Re-fold into a neat **8-inch square** and roll flat, forcing out air pockets, into a level, straight-edged square. Refrigerate.", tip: "Keep the butter between 14–18°C — pliable but cold. Too warm it smears into the dough; too cold it cracks and shatters the layers." },
        ],
      },
      {
        name: "Lamination — Day 2",
        ingredients: [],
        steps: [
          { text: "Cool the room to **20°C or below**. Deflate the chilled dough and roll into an **8-inch square**, wrap, and freeze **20 minutes**.", tip: "A cool room is non-negotiable for lamination — warmth melts the butter into the dough and you lose the distinct layers." },
          { text: "Roll the dough to **16 × 8 inches**. Set the butter block in the center at a 45° angle and fold the dough corners over to fully enclose it, pinching all seams so no butter peeks out.", tip: "Dough and butter should be the same firmness, dough slightly colder — if either is off, the layers tear or squeeze out." },
          { text: "Roll lengthwise into a **24-inch, 1/4-inch-thick** slab, pushing the pin away and toward you rather than pressing down, keeping the sides straight. Pierce any air bubbles.", tip: "Push, don't press — even pressure front-to-back keeps the butter and dough layers uniform across the whole slab." },
          { text: "Trim the short ends square. Do a **double turn**: fold each short end to just shy of the center (1/8-inch gap), then fold in half along the gap — four layers. Wrap, freeze **15 minutes**, refrigerate **1 hour**.", tip: "Resting between turns relaxes the gluten so the dough rolls out without fighting back or tearing the butter." },
          { text: "Roll out again to a long 3/8-inch slab and do a **simple turn** (fold in thirds like a letter). Wrap, freeze **15 minutes**, refrigerate **1 hour**." },
          { text: "Roll to a **14 × 17-inch** slab (15 × 16 for pain au chocolat), wrap, freeze **20 minutes**, then chill **overnight (8–12 hours)**." },
        ],
      },
      {
        name: "Shape, Proof & Bake",
        ingredients: [
          { amount: 1, unit: "", item: "egg yolk + 1 tbsp heavy cream (egg wash)" },
        ],
        steps: [
          { text: "About 4.5 hours before serving, set a skillet of simmering water in the oven (off) to create a humid proofing box. Roll the dough to **17 × 14 in**, trim to exactly 16 in long, and cut into four **4 × 14-inch** rectangles.", tip: "The steam skillet makes a 70–75°F humid environment — the ideal proof. Hotter and the butter melts out." },
          { text: "Cut each rectangle corner-to-corner into two triangles (8 total). Stretch the base to ~3 inches and gently elongate each triangle, then roll up snugly from the base, keeping the point centered, and rest on the point.", tip: "Roll snugly but don't stretch tight — the layers need room to expand, and tension makes dense, tight croissants." },
          { text: "Proof in the humid oven until **doubled, very puffy, and jiggly**, 2–2.5 hours. Don't poke them.", tip: "Underproofed croissants bake up dense and won't honeycomb — be patient and judge by the delicate wobble, not the clock alone." },
          { text: "Chill the proofed croissants **20 minutes** while you heat the oven to **375°F**. Brush the smooth surfaces with egg wash, avoiding the cut layered sides.", tip: "Brushing only the smooth tops (not the cut edges) lets the layers spring open and rise instead of being glued shut." },
          { text: "Bake **20 minutes**, then rotate and switch racks and bake another **10–15 minutes** until deeply browned. Cool completely on the sheets." },
        ],
      },
    ],
    tips: [
      "Use butter with 82%+ fat — higher fat, lower water, means cleaner layers and less steam-tearing.",
      "Keep everything cold and work fast; if the dough softens at any point, chill it before continuing.",
      "Deeply brown them — pale croissants are gummy inside; the color is the flavor.",
    ],
  },
  {
    id: "beef-wellington",
    title: "Beef Wellington",
    author: "you",
    category: "main",
    description: "Seared beef filet brushed with Dijon, wrapped in crêpe, prosciutto and mushroom duxelle, and baked in pastry — served with a rich mushroom-red wine sauce.",
    image: "",
    servings: 6,
    prepMin: 120,
    cookMin: 45,
    sections: [
      {
        name: "Prepare the Meat",
        ingredients: [
          { amount: 2, unit: "lb", item: "beef filet, trimmed" },
          { amount: 2, unit: "tbsp", item: "clarified butter or cooking oil" },
          { amount: 2, unit: "tbsp", item: "Dijon mustard" },
          { amount: null, unit: "", item: "salt and pepper" },
        ],
        steps: [
          { text: "Salt and pepper the filet and sear it **briefly** in clarified butter (around 375°F) to build a crust. Brush generously with Dijon, wrap in plastic, and refrigerate **at least 2–3 hours**.", tip: "Sear hard and fast for color only — you want a crust, not to cook the inside, since it roasts again later. Wrapping tightly sets a uniform shape." },
        ],
      },
      {
        name: "Mushroom Duxelle",
        ingredients: [
          { amount: 2, unit: "tbsp", item: "butter" },
          { amount: 10, unit: "oz", item: "portobello mushrooms, very finely chopped" },
          { amount: 0.25, unit: "cup", item: "shallots, minced" },
          { amount: 0.75, unit: "cup", item: "ham (no water added), finely diced" },
          { amount: 2, unit: "tbsp", item: "tarragon, chopped" },
          { amount: null, unit: "", item: "porcini salt (or regular salt) and pepper, to taste" },
          { amount: 1, unit: "", item: "egg white" },
        ],
        steps: [
          { text: "In a large pan, sauté the shallots in butter until **light** golden. Add the mushrooms and cook slowly until **ALL** the water has evaporated — this can take 10–12 minutes. Stir in the ham and tarragon.", tip: "Cook the mushrooms until the pan is completely dry — any residual moisture will steam the pastry soggy. This is the most important step." },
          { text: "Transfer to a glass bowl, stir in the egg white, and spread on a sheet to cool and release more moisture.", tip: "Cooling it spread thin lets even more steam escape, so the duxelle goes on cold and dry." },
        ],
      },
      {
        name: "Crêpes (about 6)",
        ingredients: [
          { amount: 2, unit: "", item: "large eggs" },
          { amount: 1, unit: "cup", item: "whole milk" },
          { amount: 1, unit: "cup", item: "all-purpose flour" },
          { amount: 2, unit: "tbsp", item: "butter, melted" },
          { amount: null, unit: "", item: "salt and pepper, to taste" },
        ],
        steps: [
          { text: "Mix all the crêpe ingredients until smooth (a blender is ideal). If you have time, rest the batter in the fridge **24 hours** for a more relaxed, less rubbery crêpe.", tip: "Resting the batter overnight relaxes the gluten so the crêpes are tender — the crêpe layer is what waterproofs the pastry from the meat's juices." },
          { text: "In the largest non-stick pan, melt a little butter at about 300°F, pour in 3–4 oz batter, and cook the crêpes thin." },
        ],
      },
      {
        name: "Wrap & Bake",
        ingredients: [
          { amount: 3, unit: "", item: "crêpes (depending on size)" },
          { amount: 9, unit: "", item: "very thin slices prosciutto" },
          { amount: 2, unit: "cup", item: "cooled mushroom duxelle" },
          { amount: 3, unit: "", item: "egg yolks + 2 tbsp milk (egg wash)" },
          { amount: null, unit: "", item: "puff pastry / dough, to wrap" },
        ],
        steps: [
          { text: "Preheat the oven to **400°F (205°C)**. Lay out 1–2 crêpes, measuring against the filet so you have enough to cover it.", tip: "The crêpe is your moisture barrier — make sure it fully wraps the meat so the pastry below stays crisp." },
          { text: "Top the crêpes with prosciutto, then cover the surface completely with duxelle.", tip: "An even, edge-to-edge layer of prosciutto and duxelle means every slice has the full flavor cross-section." },
          { text: "Wrap the filet tightly in the crêpe layer using plastic wrap and rest in the fridge while you roll out the pastry.", tip: "Chilling the wrapped log firms it into a tight cylinder, so the pastry goes on smoothly with no gaps or air pockets." },
          { text: "Encase in pastry, brush with egg wash, and bake until the pastry is deep golden and the beef reaches your target temperature." },
        ],
      },
    ],
    tips: [
      "A bone-dry duxelle and a complete crêpe wrap are the two secrets to a Wellington with crisp (not soggy) pastry.",
      "Rest the baked Wellington 10 minutes before slicing so the juices redistribute and the pastry sets.",
      "Use a meat thermometer — pull it a few degrees early since it carries over while resting.",
    ],
  },
  {
    id: "mushroom-sauce",
    title: "Mushroom Red Wine Sauce",
    author: "you",
    category: "sauce",
    description: "A glossy mushroom and red-wine pan sauce reduced with stock, balsamic and herbs, mounted with butter — perfect with beef.",
    image: "",
    servings: 6,
    prepMin: 10,
    cookMin: 35,
    ingredients: [
      { amount: 1, unit: "tbsp", item: "sweet or clarified butter" },
      { amount: 2, unit: "tbsp", item: "shallots, minced" },
      { amount: 2, unit: "cup", item: "mushrooms, sliced" },
      { amount: null, unit: "", item: "porcini salt or regular salt" },
      { amount: 1.5, unit: "tbsp", item: "garlic, chopped" },
      { amount: 2, unit: "tbsp", item: "tarragon or other herbs, chopped" },
      { amount: 2, unit: "tbsp", item: "aged balsamic vinegar (optional)" },
      { amount: 1, unit: "cup", item: "red wine" },
      { amount: 1.5, unit: "cup", item: "beef or chicken stock" },
      { amount: 1.5, unit: "tbsp", item: "cornstarch, diluted in water" },
      { amount: 3, unit: "tbsp", item: "heavy whipping cream" },
      { amount: 1, unit: "tbsp", item: "parsley, chopped" },
    ],
    steps: [
      { text: "Heat 1 tbsp butter, cook the shallots until light golden, then add the mushrooms and salt and cook until they've released most of their water, **7–10 minutes**.", tip: "Drive off the mushroom water before adding liquid — otherwise the sauce tastes thin and watery instead of deeply savory." },
      { text: "Add the herbs and garlic; when fragrant (15–20 seconds), add the balsamic and wine and reduce by about half.", tip: "Reducing the wine hard cooks off the raw alcohol and concentrates it into a glossy, jammy base." },
      { text: "Add the stock and cook **15–20 minutes**. Stir in the cream and parsley." },
      { text: "Adjust thickness with the cornstarch slurry or more butter, and at the last minute mount with as much butter as you like (the chef adds at least 2 large tablespoons).", tip: "Mounting with cold butter off the heat at the end gives the sauce its restaurant shine and silky body — don't let it boil after." },
    ],
    tips: [
      "Deglaze the beef pan with the wine to capture every bit of fond for maximum flavor.",
      "Strain the sauce for an elegant, smooth finish if serving with Wellington.",
    ],
  },
  {
    id: "beef-stock",
    title: "Roasted Beef Stock",
    author: "you",
    category: "sauce",
    description: "A deep, long-simmered beef stock boosted with caramelized onions, roasted aromatics and tomato — the backbone for sauces and soups.",
    image: "",
    servings: 16,
    prepMin: 40,
    cookMin: 270,
    ingredients: [
      { amount: 1.5, unit: "oz", item: "extra virgin olive oil" },
      { amount: 112, unit: "oz", item: "unsalted store-bought beef stock (enough to cover the vegetables)" },
      { amount: 2, unit: "lb", item: "onions, large dice" },
      { amount: 2, unit: "lb", item: "carrots, large dice (unpeeled)" },
      { amount: 2, unit: "lb", item: "celery, large dice (whole stalk)" },
      { amount: 2, unit: "", item: "leeks, 1-inch pieces (white and green)" },
      { amount: 13, unit: "sprigs", item: "fresh thyme, not chopped" },
      { amount: 18, unit: "", item: "black peppercorns" },
      { amount: 1, unit: "", item: "can (28 oz) tomato purée" },
      { amount: 1, unit: "", item: "can (6 oz) tomato paste" },
    ],
    steps: [
      { text: "Heat the oil in a large pan and cook the onions until **golden brown**, 10–15 minutes.", tip: "Deep caramelization on the onions is what gives the stock its color and rich, roasted depth — take them well past soft." },
      { text: "In a large stock pot, combine all the chopped vegetables with the caramelized onions, peppercorns, tomato purée and paste, then add the store-bought stock and stir to blend." },
      { text: "Bring to a boil, then reduce to a **very, very low simmer**. Stir occasionally and cook **3–4.5 hours**.", tip: "Keep it at a bare simmer, never a rolling boil — gentle heat keeps the stock clear instead of cloudy and greasy." },
      { text: "Strain and portion into freezable containers.", tip: "Strain through a fine sieve and cool quickly; the stock keeps 4–5 days in the fridge and months in the freezer." },
    ],
    tips: [
      "Building on store-bought stock gives you homemade depth in a fraction of the time.",
      "Freeze in usable portions so you always have a sauce base ready.",
    ],
  },
  {
    id: "mushroom-ravioli",
    title: "Mushroom Ravioli",
    author: "you",
    category: "main",
    description: "Fresh egg pasta parcels filled with a smooth, pâté-like mushroom and ricotta filling, finished in a garlicky parmesan cream sauce.",
    image: "",
    servings: 4,
    prepMin: 75,
    cookMin: 20,
    sections: [
      {
        name: "Fresh Pasta Dough",
        ingredients: [
          { amount: 0.5, unit: "kg", item: "plain flour (4 cups)" },
          { amount: 4, unit: "", item: "large eggs (plus 1 spare)" },
        ],
        steps: [
          { text: "Make a well in the flour and crack the eggs into it (keep one aside in case the dough is dry). Beat the eggs with a fork, slowly drawing in flour from the walls of the well.", tip: "Pull the flour in gradually so the eggs don't flood out — patience here gives a smooth, even dough." },
          { text: "Keep mixing, returning stray crumbs to the dough, until it thickens, then knead with both hands until smooth and the flour disappears.", tip: "Knead until the dough is satiny and springs back, but no more — over-kneading toughens it for delicate ravioli." },
          { text: "Rest the dough, covered with a bowl, for a few minutes.", tip: "Resting relaxes the gluten so the dough rolls out thin without snapping back." },
        ],
      },
      {
        name: "Mushroom Filling",
        ingredients: [
          { amount: 1, unit: "tbsp", item: "olive oil" },
          { amount: 500, unit: "g", item: "chestnut (cremini) mushrooms, sliced" },
          { amount: 2, unit: "", item: "shallots, finely chopped" },
          { amount: 1, unit: "clove", item: "garlic" },
          { amount: 1, unit: "sprig", item: "thyme" },
          { amount: 1, unit: "tbsp", item: "ricotta (heaped)" },
          { amount: 2, unit: "tbsp", item: "parmesan, freshly grated" },
          { amount: null, unit: "", item: "salt and pepper" },
        ],
        steps: [
          { text: "Sauté the shallots in olive oil until soft and translucent." },
          { text: "Add the mushrooms and cook down until reduced and softened, then add the garlic, thyme, salt and pepper and fry **1–2 minutes**. Cool **5 minutes**.", tip: "Cook the mushrooms down fully so the filling isn't wet — a dry filling won't tear or burst the pasta." },
          { text: "Blitz the cooled mushrooms with the parmesan and ricotta until **smooth and pâté-like**.", tip: "A smooth, soft filling pipes neatly and seals easily — chunky filling pokes holes in the delicate pasta." },
        ],
      },
      {
        name: "Sauce & Assembly",
        ingredients: [
          { amount: 0.5, unit: "tbsp", item: "olive oil" },
          { amount: 250, unit: "ml", item: "double (heavy) cream" },
          { amount: 2, unit: "tbsp", item: "parmesan, freshly grated" },
          { amount: 1, unit: "clove", item: "garlic" },
          { amount: 1, unit: "pinch", item: "nutmeg" },
          { amount: 1, unit: "sprig", item: "thyme" },
          { amount: null, unit: "", item: "salt and pepper" },
        ],
        steps: [
          { text: "Roll the pasta from the widest setting down to the third-last (usually 7). Place heaped teaspoons of filling 1 inch apart on a sheet of pasta.", tip: "Don't wet the edges unless the pasta is very dry — dry, clean edges actually seal more reliably." },
          { text: "Fold the pasta over the filling, pat down to remove air, and seal around each mound with your fingers (mezzalune), or top with a second sheet for classic ravioli.", tip: "Press out every bit of air around the filling — trapped air makes ravioli burst or wrinkle in the water." },
          { text: "Cut out with a cutter and rest on a semolina-dusted surface. Boil in salted water about **4 minutes**.", tip: "A semolina-dusted surface keeps the parcels from sticking; cook in plenty of well-salted water so they don't clump." },
          { text: "For the sauce, fry the garlic in a little oil **1 minute**, add the cream, thyme, nutmeg, salt and pepper, and bring to a boil. Boil **30–40 seconds**, lower the heat, and stir in the parmesan until slightly thickened.", tip: "Add the parmesan off a hard boil so it melts smoothly instead of going stringy." },
          { text: "Lift the cooked ravioli straight from the water into the sauce, toss, and serve.", tip: "A little clinging pasta water helps the sauce coat each parcel glossily." },
        ],
      },
    ],
    tips: [
      "Make sure the mushroom filling is smooth and soft like pâté; use a piping bag or teaspoon to fill.",
      "To freeze, lay the ravioli in a single layer (not touching) until solid, then bag — frozen they cook straight from the freezer.",
    ],
  },
  {
    id: "peppercorn-sauce",
    title: "Peppercorn Sauce (Make-Ahead)",
    author: "you",
    category: "sauce",
    description: "A glossy, restaurant-grade peppercorn sauce built on Cognac and rich stock — made ahead, then finished with butter the moment your guests arrive.",
    image: "",
    servings: 6,
    prepMin: 10,
    cookMin: 25,
    sections: [
      {
        name: "The Sauce Base",
        ingredients: [
          { amount: 6, unit: "tbsp", item: "cracked black pepper" },
          { amount: 3, unit: "tbsp", item: "salt (adjust if your stock is salted — see tip)" },
          { amount: 6, unit: "tbsp", item: "clarified butter" },
          { amount: 6, unit: "tbsp", item: "Cognac" },
          { amount: 3, unit: "cup", item: "rich veal or beef stock" },
          { amount: 0.75, unit: "cup", item: "heavy whipping cream" },
          { amount: 3, unit: "tbsp", item: "green peppercorns, drained" },
          { amount: 6, unit: "tbsp", item: "unsalted sweet butter (for finishing)" },
        ],
        steps: [
          { text: "After cooking your steaks or roasts, retain about **3 tablespoons of beef fat** in the pan.", tip: "Those rendered drippings are pure flavour — never wash the pan before you've built the sauce in it." },
          { text: "Deglaze the pan carefully with the **Cognac**. If you flambé, be cautious — the fumes can ignite dramatically.", tip: "Pull the pan off the flame before adding alcohol, then return it; this controls the flare-up and protects your eyebrows." },
          { text: "Scrape up the browned bits (fond) from the bottom with a wooden spoon — these add deep flavour to the sauce." },
          { text: "Add the **stock, cream and green peppercorns**. Bring to a gentle boil, then reduce to medium." },
          { text: "Reduce until the sauce lightly coats the back of a spoon, about **8–12 minutes**.", tip: "Run a finger across the coated spoon — if the line holds clean, it's ready. Reduce too far and it'll turn pasty once chilled." },
          { text: "Remove from the heat. **Do not add the sweet butter yet.** Cool 20–30 minutes, then refrigerate in an airtight container up to 3 days.", tip: "Holding the butter until service is the make-ahead secret — butter whisked in now would split on reheating." },
        ],
      },
      {
        name: "Finishing & Serving",
        ingredients: [],
        steps: [
          { text: "Pour the sauce into a small saucepan and reheat gently over medium-low, stirring, until hot and smooth.", tip: "Never let it boil at this stage — boiling separates the cream and you lose the silky body." },
          { text: "Off the heat, whisk in the **sweet butter** (6 tbsp, or to taste) until fully emulsified and glossy.", tip: "Add the cold butter a knob at a time, whisking constantly — this 'monter au beurre' is what gives the sauce its restaurant shine." },
          { text: "Taste and adjust seasoning, then spoon over freshly grilled steaks or roasts and serve immediately." },
        ],
      },
    ],
    tips: [
      "If your stock is already salted or reduced, hold back on the 3 tbsp salt and season only at the very end.",
      "To mellow the pepper's heat, simmer the peppercorns briefly in the stock before the cream goes in.",
      "If the chilled sauce is too thick when you reheat, loosen it with a splash of warm stock or cream.",
      "Make it to the refrigeration step in the morning (or the day before) and finish with butter à la minute for a fresh, restaurant-quality result.",
    ],
  },
  {
    id: "ajada",
    title: "Ajada (Garlic Bread Emulsion)",
    author: "you",
    category: "sauce",
    description: "A silky Sephardic garlic emulsion thickened with soaked bread and egg white — punchy, lemony, and smooth as mayonnaise.",
    image: "",
    servings: 6,
    prepMin: 15,
    cookMin: 0,
    ingredients: [
      { amount: 7, unit: "", item: "slices white bread, crusts removed" },
      { amount: 12, unit: "", item: "garlic cloves" },
      { amount: 5, unit: "tsp", item: "salt" },
      { amount: 5, unit: "tsp", item: "lemon juice" },
      { amount: 4, unit: "", item: "egg whites" },
      { amount: 200, unit: "ml", item: "canola oil" },
      { amount: null, unit: "", item: "water, for soaking the bread" },
    ],
    steps: [
      { text: "Soak the crustless bread in water for **2 minutes**, then squeeze thoroughly to remove all excess water. Set the damp bread aside.", tip: "Squeeze the bread almost dry — leftover water thins the emulsion and makes it weep later." },
      { text: "Put the garlic, salt and lemon juice in a blender. Pulse until the garlic is fully minced into a rough paste.", tip: "Removing the green germ from the centre of each clove first gives a smoother, less bitter flavour." },
      { text: "Add the **egg whites** and blend on high until frothy and well combined." },
      { text: "With the motor running, pour the **canola oil in a very thin, steady stream** through the top until the mixture thickens into a mayonnaise-like emulsion.", tip: "Go slow at the start — adding oil too fast is the #1 cause of a broken emulsion. A pencil-thin stream is the goal." },
      { text: "With the blender still running, add the **squeezed bread one piece at a time** through the top." },
      { text: "Blend until the bread is fully incorporated and the mixture is a smooth, thick paste." },
    ],
    tips: [
      "Serve cold, alongside grilled fish, roasted vegetables, or as a dip with warm bread.",
      "If it ever breaks, start a fresh egg white in a clean blender and drizzle the broken mixture into it slowly to bring it back.",
    ],
  },
  {
    id: "challah",
    title: "Challah",
    author: "mom",
    category: "bread",
    description: "Soft, golden braided challah with a tender crumb — a family staple for the table.",
    image: "",
    servings: 12,
    prepMin: 40,
    cookMin: 25,
    ingredients: [
      { amount: 1, unit: "kg", item: "flour" },
      { amount: 2, unit: "", item: "packets active dry yeast" },
      { amount: 5, unit: "tbsp", item: "sugar" },
      { amount: 1, unit: "tbsp", item: "salt" },
      { amount: 0.25, unit: "cup", item: "canola oil" },
      { amount: 2.5, unit: "cup", item: "water" },
    ],
    steps: [
      { text: "Put the **flour** in the mixer with the **2 packets of yeast** and the **5 tbsp sugar**.", tip: "Keep the salt away from direct contact with the yeast — make little wells in the flour and put the 1 tbsp salt in the holes, so it doesn't kill the yeast." },
      { text: "Start the mixer and add the **canola oil**." },
      { text: "While mixing, add the **water** gradually (similar to making Boyos — use the guitara/dough hook).", tip: "Add the water bit by bit; you want a dough that pulls away from the bowl but still feels soft, not stiff." },
      { text: "Once the dough is firm and smooth, let it rest until it **rises and doubles**.", tip: "A warm, draft-free spot speeds the rise — inside an off oven with just the light on is perfect." },
      { text: "Punch down and mix again, then let it **rise a second time**.", tip: "The second rise is what gives challah its fine, fluffy crumb — don't skip it." },
      { text: "Divide into **160 g balls** and braid using **4 strands** of dough per loaf.", tip: "Roll each strand evenly and taper the ends — even strands make a neat, bakery-style braid." },
      { text: "Preheat the oven to **410°F** and bake the challah until deep golden.", tip: "Brush with egg wash before baking for that glossy, lacquered crust." },
    ],
    tips: [
      "For a richer loaf, add an egg to the dough and use an egg-yolk wash before baking.",
      "Tap the bottom of a baked loaf — a hollow sound means it's done.",
    ],
  },
  {
    id: "agedashi-tofu",
    title: "Japanese Agedashi Tofu",
    author: "you",
    category: "appetizer",
    description: "Crisp cornstarch-coated tofu in a warm dashi broth, finished with grated daikon, bonito and green onion.",
    image: "",
    servings: 6,
    prepMin: 15,
    cookMin: 15,
    sections: [
      {
        name: "Tofu",
        ingredients: [
          { amount: 2.5, unit: "", item: "packs firm tofu" },
          { amount: 2.5, unit: "cup", item: "corn starch, for coating" },
          { amount: null, unit: "", item: "neutral oil for frying (or spray oil for air fryer)" },
        ],
        steps: [
          { text: "Drain the tofu and pat dry thoroughly with paper towels, then cut into **1-inch cubes**.", tip: "Press the tofu under a weighted plate for 10 minutes first — the drier the tofu, the crispier the crust and the safer the fry." },
          { text: "Lightly coat all sides with corn starch and let rest **1–2 minutes** so the coating sticks.", tip: "That short rest lets the starch hydrate into a thin shell that fries up shatteringly crisp." },
        ],
      },
      {
        name: "Sauce",
        ingredients: [
          { amount: 3, unit: "cup", item: "dashi stock (or mushroom stock for vegetarian)" },
          { amount: 12, unit: "tbsp", item: "soy sauce" },
          { amount: 12, unit: "tbsp", item: "mirin" },
        ],
        steps: [
          { text: "Combine the **dashi, soy sauce and mirin** in a small pot. Bring to a simmer over medium heat and cook **5 minutes**, then set aside.", tip: "Keep it warm but don't reduce it hard — agedashi broth should be light and pourable, not a thick glaze." },
        ],
      },
      {
        name: "Fry & Assemble",
        ingredients: [
          { amount: 7.5, unit: "tbsp", item: "grated daikon" },
          { amount: 2.5, unit: "tbsp", item: "bonito flakes" },
          { amount: 2.5, unit: "", item: "stalks green onion, finely chopped" },
        ],
        steps: [
          { text: "Heat oil over medium-high and fry the tofu **4–5 minutes**, turning occasionally, until golden and crispy.", tip: "Don't crowd the pan — frying in batches keeps the oil hot so the tofu crisps instead of steaming." },
          { text: "Place fried tofu in serving bowls and **pour the hot sauce around (not over)** so the crust stays crisp.", tip: "Pour the broth at the table, around the tofu — it keeps the coating crunchy until the first bite." },
          { text: "Top with grated daikon, green onion and bonito flakes, and serve immediately." },
        ],
      },
    ],
    tips: [
      "Use the freshest firm tofu you can find; silken will fall apart in the fryer.",
      "Watch the bonito flakes dance on the hot tofu — add them last so they stay lively.",
    ],
  },
  {
    id: "almond-milk-rosette",
    title: "Almond Rosétte (Almond Milk Syrup)",
    author: "mom",
    category: "drink",
    description: "A homemade almond milk reduced into a fragrant syrup with rose or orange-blossom water — dilute with cold water to serve.",
    image: "",
    servings: 8,
    prepMin: 30,
    cookMin: 35,
    ingredients: [
      { amount: 690, unit: "g", item: "almonds" },
      { amount: 300, unit: "g", item: "sugar" },
      { amount: null, unit: "", item: "rose water (optional)" },
      { amount: null, unit: "", item: "almond extract" },
    ],
    steps: [
      { text: "Blanch the almonds in boiling water for **5 minutes** until the skins separate easily, then transfer to cold water to cool, and drain.", tip: "The cold-water shock makes the skins slip right off between your fingers — peel while still warm." },
      { text: "Peel the almonds and grind them in a food processor." },
      { text: "Boil the ground almonds with **6 cups of water** for 5 minutes. Strain into a large bowl, squeezing the almonds well to extract all their flavour (this is your almond milk).", tip: "Press the pulp hard in the strainer — most of the flavour and body lives in that last squeeze." },
      { text: "Boil the almond milk with the **sugar** until the syrup thickens enough to coat the back of a spoon, about **20–30 minutes**. At the end, add a drop of lemon juice, almond extract, or orange-blossom water.", tip: "Stir often near the end — almond syrup catches and scorches quickly once it thickens." },
      { text: "Keep in a bottle. To serve, dilute with cold water to taste." },
    ],
    tips: [
      "For a sugar-free version, omit the sugar and thicken the strained almond water with a little xanthan gum — but expect a thinner mouthfeel, since sugar adds body as well as sweetness.",
      "Store the syrup in the fridge; it keeps for a couple of weeks in a clean bottle.",
    ],
  },
  {
    id: "malabi",
    title: "Malabi (Rose Milk Pudding)",
    author: "mom",
    category: "dessert",
    description: "A delicate, wobbly milk pudding scented with rose water, crowned with a bright berry syrup and crushed pistachios and coconut.",
    image: "",
    servings: 6,
    prepMin: 20,
    cookMin: 15,
    sections: [
      {
        name: "The Cream",
        ingredients: [
          { amount: 3.5, unit: "cup", item: "milk (or coconut milk)" },
          { amount: 0.5, unit: "cup", item: "heavy whipping cream (or coconut cream)" },
          { amount: 0.5, unit: "cup", item: "corn starch" },
          { amount: 0.5, unit: "cup", item: "sugar" },
          { amount: 0.5, unit: "tsp", item: "rose water" },
        ],
        steps: [
          { text: "In a small pot, whisk together the **milk, cream, corn starch, sugar and rose water** until there are no lumps of corn starch.", tip: "Whisk the corn starch into the COLD liquid before any heat — adding it to hot milk guarantees lumps." },
          { text: "Set over medium-high heat and bring to a boil, whisking constantly. The moment it bubbles it will thicken; cook another **30–60 seconds**.", tip: "Don't walk away — corn starch sets fast and will catch on the bottom the instant you stop whisking." },
          { text: "Pour into serving glasses (easiest via a pouring jug), cover with plastic wrap touching the surface, cool, and chill fully in the fridge.", tip: "Press the wrap directly onto the surface so no skin forms on top of the pudding." },
        ],
      },
      {
        name: "Bright Red Berry Syrup",
        ingredients: [
          { amount: 300, unit: "g", item: "frozen mixed berries" },
          { amount: 0.5, unit: "cup", item: "sugar" },
          { amount: 0.5, unit: "cup", item: "water" },
          { amount: 0.5, unit: "tsp", item: "rose water" },
          { amount: 1, unit: "tsp", item: "corn starch" },
        ],
        steps: [
          { text: "Put the **berries, sugar, water and rose water** in a small pot over high heat. Bring to a boil, lower to a gentle simmer, and cook about **10 minutes**." },
          { text: "Mix the **1 tsp corn starch** with 1 tsp water, stir it into the berries, and cook another **30 seconds** to thicken.", tip: "Slurry the starch with cold water first; tipping dry starch into hot syrup makes gummy lumps." },
          { text: "Strain the sauce through a sieve, pressing gently with a spoon, into a bowl. Cool slightly, then chill fully." },
        ],
      },
      {
        name: "To Serve",
        ingredients: [
          { amount: null, unit: "", item: "chopped pistachios or peanuts" },
          { amount: null, unit: "", item: "shredded coconut" },
        ],
        steps: [
          { text: "Pour the red syrup over each chilled malabi and scatter with pistachios and coconut.", tip: "Add the toppings just before serving so the nuts and coconut stay crunchy against the silky pudding." },
        ],
      },
    ],
    tips: [
      "Serve cold and freshly topped — malabi is all about the contrast of cool, wobbly cream and bright, tart syrup.",
      "Coconut milk and coconut cream make an excellent dairy-free version with the same texture.",
    ],
  },
  {
    id: "cacio-e-pepe-cappelletti",
    title: "Cacio E Pepe y Cappelletti y vodka",
    author: "you",
    category: "main",
    description: "An ambitious project pasta — saffron cappelletti stuffed with a Panela cacio e pepe filling, finished in a spicy vodka emulsion.",
    image: "",
    servings: 6,
    prepMin: 120,
    cookMin: 30,
    sections: [
      {
        name: "The Saffron-Infused Silky Dough",
        ingredients: [
          { amount: 750, unit: "g", item: "Tipo \"00\" flour" },
          { amount: 4, unit: "", item: "Large whole eggs (Room temperature)" },
          { amount: 6, unit: "", item: "Large egg yolks (Room temperature)" },
          { amount: 1, unit: "tbsp", item: "Extra virgin olive oil" },
          { amount: 0.75, unit: "tsp", item: "Kosher salt" },
          { amount: 1, unit: "", item: "generous pinch (about 1/2 tsp) High-quality saffron threads" },
          { amount: 1, unit: "tbsp", item: "Hot water" },
        ],
        steps: [
          "Bloom the Saffron: Place the saffron threads in a mortar and pestle with a tiny pinch of coarse salt (the salt acts as an abrasive). Grind it into a fine powder. Transfer the powder to a small bowl and pour in the 1 tablespoon of hot water. Let it steep for 15 to 20 minutes until the water turns a vibrant, dark crimson.",
          "The Wet Mix: In a bowl, whisk together the whole eggs, egg yolks, olive oil, the 3/4 tsp of salt, and the entire saffron-infused liquid (scrape every bit of color out of the bowl).",
          "The Well: Mound the flour on a clean wooden board and create a deep, wide well in the center. Pour the golden egg mixture into the well.",
          "Incorporate: Using a fork, continuously beat the wet ingredients while slowly pulling in flour from the inner walls of the well.",
          "The Knead: Once the mixture forms a shaggy dough, use your hands to knead it aggressively for 10 to 12 minutes.",
          "The Rest: Wrap the dough airtight in plastic wrap. Let it rest at room temperature for exactly 45 minutes.",
        ],
      },
      {
        name: "The Panela Cacio e Pepe Filling",
        ingredients: [
          { amount: 1.8, unit: "lb", item: "Queso Panela (Crumbled)" },
          { amount: 1, unit: "cup", item: "plus 2 tbsp Parmigiano Reggiano (Finely grated)" },
          { amount: 0.333, unit: "cup", item: "Heavy cream (Cold)" },
          { amount: 2, unit: "tbsp", item: "Whole black peppercorns" },
          { amount: null, unit: "", item: "Zest of 1.5 Lemons" },
          { amount: null, unit: "", item: "Kosher salt (To taste)" },
        ],
        steps: [
          "Toast the Pepper: Place the whole black peppercorns in a dry skillet over medium heat. Toast for 2 to 3 minutes, shaking the pan frequently, until highly fragrant.",
          "Process the Panela: Place the crumbled Queso Panela into a food processor. Pulse several times until it reaches a fine, granular texture.",
          "Bind the Filling: Turn the food processor to low. Slowly stream in 1/3 cup of the heavy cream.",
          "Fold and Season: Transfer the whipped Panela to a large mixing bowl. Fold in the finely grated Parmigiano Reggiano, the toasted black pepper, and the lemon zest.",
          "Chill: Transfer the filling to a pastry bag (or a large ziplock bag). Refrigerate for 30 to 45 minutes to firm up the fats.",
        ],
      },
      {
        name: "Rolling & Shaping (The Atlas 150)",
        ingredients: [

        ],
        steps: [
          "Section the Dough: Cut off a quarter of the rested dough. Immediately re-wrap the remaining dough to keep it from drying out.",
          "Laminate: Set your Marcato Atlas 150 to setting 0. Pass the dough through. Fold the dough into thirds and pass it through setting 0 again.",
          "Roll for Thickness: Pass the laminated sheet sequentially through settings 1, 2, 3, 4, 5, and 6.",
          "Cut and Pipe: Lay the golden sheet flat and cut it into 2.5-inch squares.",
          "The Fold: Fold the square in half diagonally to create a triangle.",
          "Store: Place the finished cappelletti on a baking sheet heavily dusted with semolina flour.",
        ],
      },
      {
        name: "The Spicy Vodka Sauce & Emulsion — The Base",
        ingredients: [
          { amount: 0.25, unit: "cup", item: "Extra virgin olive oil" },
          { amount: 3, unit: "tbsp", item: "European butter" },
          { amount: 3, unit: "", item: "Shallots (Minced finely)" },
          { amount: 4, unit: "cloves", item: "Garlic (Microplaned)" },
          { amount: 9, unit: "oz", item: "Mutti Double-Concentrated Tomato Paste (2 tubes)" },
          { amount: 2, unit: "tbsp", item: "Pure Calabrian chili paste" },
          { amount: 0.75, unit: "cup", item: "Vodka" },
        ],
        steps: [

        ],
      },
      {
        name: "The Spicy Vodka Sauce & Emulsion — The Finish",
        ingredients: [
          { amount: 3, unit: "cup", item: "Heavy cream (Room temperature)" },
          { amount: 0.5, unit: "cup", item: "Parmigiano Reggiano (Freshly grated)" },
          { amount: null, unit: "", item: "Fresh basil (Torn)" },
          { amount: null, unit: "", item: "Kosher salt" },
        ],
        steps: [
          "Sweat the Aromatics: In a heavy-bottomed pan, heat the olive oil and butter over medium-low. Add the minced shallots with a pinch of salt.",
          "The Pincage: Squeeze the 9 oz of Mutti tomato paste into the pan. Increase the heat to medium.",
          "Deglaze: Remove the pan from the heat briefly. Pour in the vodka.",
          "Warm the Base: 15 minutes before serving, place your tomato-vodka base into a large, wide skillet over medium-low heat.",
          "Add the Cream: Slowly stream in the room-temperature heavy cream while stirring continuously.",
          "Boil the Pasta: Drop the saffron cappelletti into heavily salted, rapidly boiling water. Cook for 2 to 3 minutes.",
        ],
      },
    ],
    tips: [
    "This resting period hydrates the starches and relaxes the gluten network, making the dough pliable rather than rubbery.",
    "Piping cold, firm filling helps maintain sharp, precise angles when folding the pasta.",
    ],
  },
  {
    id: "moms-shakshuka",
    title: "Mom's Shakshuka",
    author: "mom",
    category: "breakfast",
    description: "Eggs gently poached in a smoky, slow-cooked pepper and tomato sauce. The dish that fills the whole kitchen with the smell of cumin.",
    image: "",
    servings: 4,
    prepMin: 15,
    cookMin: 30,
    ingredients: [
      { amount: 3,   unit: "tbsp", item: "olive oil" },
      { amount: 1,   unit: "",     item: "onion, finely diced" },
      { amount: 2,   unit: "",     item: "red bell peppers, sliced" },
      { amount: 4,   unit: "",     item: "garlic cloves, minced" },
      { amount: 2,   unit: "tsp",  item: "ground cumin" },
      { amount: 1,   unit: "tsp",  item: "sweet paprika" },
      { amount: 0.25,unit: "tsp",  item: "cayenne (optional)" },
      { amount: 800, unit: "g",    item: "crushed tomatoes" },
      { amount: 6,   unit: "",     item: "eggs" },
      { amount: null,unit: "",     item: "salt & black pepper to taste" },
      { amount: null,unit: "",     item: "fresh parsley & crumbled feta to finish" },
    ],
    steps: [
      "Warm the olive oil in a wide skillet over medium heat. Add the onion and peppers with a pinch of salt and cook slowly for 12–15 minutes until soft and sweet.",
      "Add the garlic, cumin, paprika and cayenne. Stir for 1 minute until fragrant.",
      "Pour in the crushed tomatoes. Simmer **uncovered** for 10–15 minutes until the sauce thickens and a spoon leaves a trail.",
      "Make wells in the sauce and crack an egg into each. Cover and cook 6–8 minutes until whites are set but yolks stay runny.",
      "Scatter with parsley and feta. Serve straight from the pan with warm bread.",
    ],
    tips: [
      "Season the sauce *before* adding the eggs — once the eggs are in you can't stir it without breaking the yolks.",
      "For glossy, restaurant-style yolks, baste the tops with a spoon of hot sauce instead of overcooking the whole egg.",
      "A pinch of sugar tames overly acidic tinned tomatoes — taste first, it's often unnecessary with good ones.",
    ],
  },
  {
    id: "weeknight-cacio-e-pepe",
    title: "Cacio e Pepe",
    author: "you",
    category: "main",
    description: "Three ingredients, infinite respect. Pasta in a silky pecorino-and-pepper sauce built entirely from starchy water and patience.",
    image: "",
    servings: 2,
    prepMin: 5,
    cookMin: 15,
    ingredients: [
      { amount: 200, unit: "g",   item: "spaghetti or tonnarelli" },
      { amount: 100, unit: "g",   item: "Pecorino Romano, finely grated" },
      { amount: 2,   unit: "tsp", item: "black peppercorns, freshly cracked" },
      { amount: null,unit: "",    item: "fine sea salt for the pasta water" },
    ],
    steps: [
      "Toast the cracked pepper in a dry pan for 30 seconds until fragrant. This wakes up the oils.",
      "Boil the pasta in **lightly** salted water (the cheese is salty) until 2 minutes shy of al dente. Save 2 cups of the starchy water.",
      "In a bowl, whisk the pecorino with a few tablespoons of *warm* (not boiling) pasta water into a smooth, thick paste.",
      "Add the toasted pepper and pasta to the pan with a splash of pasta water. Toss hard over low heat.",
      "Off the heat, fold in the cheese paste, tossing constantly and adding water by the spoonful until the sauce turns creamy and clings.",
    ],
    tips: [
      "Cheese hates boiling water — it seizes into rubbery clumps. Let the pan cool for 30 seconds before the pecorino goes in. This is the whole technique.",
      "Grate the pecorino as fine as dust; coarse shreds won't emulsify and you'll get a grainy sauce.",
      "Finish the pasta *in* the sauce, not the sauce on the pasta. The starch released in the final toss is what makes it glossy.",
    ],
  },
  {
    id: "brown-butter-choc-chip",
    title: "Brown Butter Chocolate Chip Cookies",
    author: "you",
    category: "dessert",
    description: "Deeply nutty, chewy in the middle, crisp at the edges, with pools of dark chocolate and a flake of sea salt on top.",
    image: "",
    servings: 18,
    prepMin: 20,
    cookMin: 12,
    ingredients: [
      { amount: 170, unit: "g",   item: "unsalted butter" },
      { amount: 150, unit: "g",   item: "brown sugar" },
      { amount: 100, unit: "g",   item: "white sugar" },
      { amount: 1,   unit: "",    item: "egg + 1 yolk" },
      { amount: 2,   unit: "tsp", item: "vanilla extract" },
      { amount: 230, unit: "g",   item: "all-purpose flour" },
      { amount: 0.75,unit: "tsp", item: "baking soda" },
      { amount: 0.75,unit: "tsp", item: "fine salt" },
      { amount: 200, unit: "g",   item: "dark chocolate, chopped" },
      { amount: null,unit: "",    item: "flaky sea salt to finish" },
    ],
    steps: [
      "Melt the butter and keep cooking, swirling, until it foams then turns amber and smells of toffee. Cool 10 minutes.",
      "Whisk the brown butter with both sugars, then the egg, yolk and vanilla until smooth and glossy (about 1 minute).",
      "Fold in flour, baking soda and salt until just combined, then the chopped chocolate.",
      "**Rest the dough** at least 30 minutes (overnight is better) so the flour hydrates and the flavour deepens.",
      "Scoop into balls, top with a few extra chocolate shards, and bake at 180°C / 355°F for 10–12 minutes until edges are set but centres look underdone. Finish with flaky salt.",
    ],
    tips: [
      "Pull them when the centres still look slightly raw — carry-over heat finishes them on the tray and keeps the middle fudgy.",
      "Resting the dough isn't optional for great cookies; it's the difference between flat-and-greasy and chewy-with-toffee-notes.",
      "Bang the tray on the counter once halfway through baking for that bakery-style rippled, crinkled edge.",
    ],
  },
  {
    id: "moms-chicken-soup",
    title: "Mom's Golden Chicken Soup",
    author: "mom",
    category: "soup",
    description: "The cure-all. A clear, deeply savory broth simmered low and slow until it turns liquid gold, with tender chicken and soft vegetables.",
    image: "",
    servings: 6,
    prepMin: 20,
    cookMin: 120,
    ingredients: [
      { amount: 1.5, unit: "kg",  item: "whole chicken (or thighs + wings)" },
      { amount: 3,   unit: "L",   item: "cold water" },
      { amount: 3,   unit: "",    item: "carrots, in chunks" },
      { amount: 3,   unit: "",    item: "celery stalks, in chunks" },
      { amount: 2,   unit: "",    item: "onions, halved" },
      { amount: 1,   unit: "",    item: "whole garlic head, halved" },
      { amount: 1,   unit: "bunch",item: "fresh dill & parsley, tied" },
      { amount: 2,   unit: "",    item: "bay leaves" },
      { amount: null,unit: "",    item: "salt & whole peppercorns to taste" },
    ],
    steps: [
      "Put the chicken in a big pot, cover with **cold** water, and bring slowly to a bare simmer. Skim off the grey foam as it rises — this is what keeps the broth clear.",
      "Add the vegetables, garlic, herbs, bay and peppercorns. Never let it boil hard; keep it at a lazy simmer.",
      "Simmer gently, partly covered, for 1.5–2 hours, skimming occasionally.",
      "Lift out the chicken, pull the meat from the bones, and return the meat. Strain the broth if you want it crystal clear.",
      "Season at the very end and finish with a handful of fresh dill.",
    ],
    tips: [
      "Always start in COLD water. A hot start seals the proteins and gives you a cloudy, flat-tasting broth.",
      "Never boil a stock — bubbling emulsifies the fat into the liquid and turns it greasy and murky. A few lazy bubbles is all you want.",
      "Salt only at the end. The broth concentrates as it reduces, and early salt almost always over-seasons it.",
    ],
  },
  {
    id: "burrata-tomato-salad",
    title: "Burrata with Heirloom Tomatoes",
    author: "you",
    category: "appetizer",
    description: "Peak-summer on a plate: cold creamy burrata, sweet tomatoes at room temperature, torn basil, good oil. Almost no cooking, all technique of taste.",
    image: "",
    servings: 4,
    prepMin: 15,
    cookMin: 0,
    ingredients: [
      { amount: 2,   unit: "",     item: "balls of burrata" },
      { amount: 600, unit: "g",    item: "mixed heirloom tomatoes" },
      { amount: 1,   unit: "handful",item: "fresh basil" },
      { amount: 4,   unit: "tbsp", item: "extra-virgin olive oil" },
      { amount: 1,   unit: "tsp",  item: "flaky sea salt" },
      { amount: null,unit: "",     item: "black pepper & a little aged balsamic" },
    ],
    steps: [
      "Take the burrata out of the fridge 20 minutes before serving — cold dulls its flavour and texture.",
      "Cut the tomatoes into varied shapes (wedges, slices, halved cherries) and salt them. Let them sit 10 minutes to draw out their juice.",
      "Arrange tomatoes on a plate, tuck the burrata in the middle and tear it open.",
      "Spoon over the tomato juices, drizzle generously with oil, scatter basil, and finish with flaky salt, pepper and a thread of balsamic.",
    ],
    tips: [
      "Salt the tomatoes early and on their own — the released juices become a free, intense dressing you'd otherwise throw away.",
      "Serve everything at room temperature. Fridge-cold mutes both the tomatoes' sweetness and the burrata's cream.",
      "Tear the burrata, don't slice it. The ragged edges catch oil and juice far better than clean cuts.",
    ],
  },
  {
    id: "smashed-roast-potatoes",
    title: "Crispy Smashed Roast Potatoes",
    author: "mom",
    category: "side",
    description: "Boiled until tender, smashed flat, then roasted hard until the edges shatter. Crunchy outside, fluffy inside — the best part of any dinner.",
    image: "",
    servings: 4,
    prepMin: 10,
    cookMin: 45,
    ingredients: [
      { amount: 1,   unit: "kg",   item: "baby potatoes" },
      { amount: 4,   unit: "tbsp", item: "olive oil or duck fat" },
      { amount: 4,   unit: "",     item: "garlic cloves, crushed" },
      { amount: 3,   unit: "sprigs",item: "rosemary" },
      { amount: null,unit: "",     item: "salt & pepper, generously" },
    ],
    steps: [
      "Boil the potatoes in well-salted water until a knife slides in easily, about 20 minutes. Drain and steam-dry 5 minutes.",
      "Place on an oiled tray and press each one flat with a glass or masher until the skin cracks.",
      "Drizzle generously with oil, season hard, and tuck garlic and rosemary around them.",
      "Roast at 220°C / 430°F for 25–30 minutes, flipping once, until deeply golden and crackling at the edges.",
    ],
    tips: [
      "Let the drained potatoes steam-dry in the colander for a few minutes — surface moisture is the enemy of crispiness.",
      "Don't crowd the tray. Potatoes touching each other steam instead of roast; give every one breathing room.",
      "Season the moment they come out, while the oil is still hot and the salt will stick.",
    ],
  },
];

/* ---- Saved external recipe links you both want to try ----
   Add to this array the same way — or use the "Add link" button on the site. */
const LINKS = [
  { title: "NYT Cooking — No-Knead Bread", url: "https://cooking.nytimes.com/recipes/11376-no-knead-bread", addedBy: "you", note: "For the weekend — try with the dutch oven" },
  { title: "Kenji's Ultimate Bolognese", url: "https://www.seriouseats.com/the-best-slow-cooked-bolognese-sauce-recipe", addedBy: "mom", note: "Mom wants to make this for Sunday dinner" },
  { title: "Half Baked Harvest — Marry Me Chicken", url: "https://www.halfbakedharvest.com/marry-me-chicken/", addedBy: "you", note: "Saw this everywhere, looks incredible" },
];
